window.ECA_S1_FORM = {
  dayOrder: ["mon", "wed", "thu", "fri"],
  days: {
    mon: { zh: "星期一", en: "Monday" },
    wed: {
      zh: "星期三",
      en: "Wednesday",
      noteZh: "星期三包括制服團隊及腦力攻防戰。",
      noteEn: "Wednesday includes uniform groups and Brain Battle.",
    },
    thu: { zh: "星期四", en: "Thursday" },
    fri: { zh: "星期五", en: "Friday" },
  },
  interview: [
    "無伴奏合唱團",
    "合唱團",
    "跳舞",
    "足球",
    "女子籃球",
    "田徑",
    "羽毛球",
    "乒乓球",
    "男女子排球",
    "欖球",
    "男子籃球",
  ],
  needLevel: ["小提琴(1)", "小提琴(2)", "大提琴", "單簧管", "長笛", "銅管樂"],
  clubAlias: {
    "Debate Team": "英文辯論",
    跳舞: "舞蹈組",
    "小提琴(1)": "管弦樂班",
    "小提琴(2)": "管弦樂班",
    大提琴: "管弦樂班",
    單簧管: "管弦樂班",
    長笛: "管弦樂班",
    銅管樂: "管弦樂班",
  },
  cat: {
    學術: { zh: "學術", en: "Academic" },
    藝術: { zh: "藝術", en: "Arts" },
    體育: { zh: "體育", en: "Sports" },
    制服: { zh: "制服", en: "Uniform" },
  },
  activities: {
    mon: [
      ["女子籃球", "Girls Basketball", "體育"],
      ["男子籃球", "Boys Basketball", "體育"],
      ["手鈴", "Handbell", "藝術"],
      ["羽毛球", "Badminton", "體育"],
      ["視覺藝術小組", "Visual Arts Group", "藝術"],
      ["Debate Team", "Debate Team", "學術"],
      ["桌上遊戲", "Board Games", "藝術"],
      ["MKPC On Air 廣播隊", "MKPC On Air", "藝術", "MKPC On Air"],
      ["中文辯論", "Chinese Debating", "學術"],
      ["法文班", "French Class", "學術"],
      ["小提琴(1)", "Violin (1)", "藝術"],
      ["大提琴", "Cello", "藝術"],
      ["單簧管", "Clarinet", "藝術"],
      ["長笛", "Flute", "藝術"],
      ["無伴奏合唱團", "A Cappella", "藝術"],
      ["跳舞", "Dance", "藝術"],
      ["田徑", "Athletics", "體育"],
      ["足球", "Football", "體育"],
    ],
    wed: [
      ["腦力攻防戰", "Brain Battle", "學術"],
      ["女童軍", "Girl Guides", "制服"],
      ["基督少年軍", "Boys' Brigade", "制服"],
      ["交通安全隊", "Road Safety Patrol", "制服"],
      ["童軍", "Scouts", "制服"],
      ["銀樂隊", "Marching Band", "制服"],
      ["升旗隊", "Flag Raising Team", "制服"],
    ],
    thu: [
      ["男女子排球", "Volleyball", "體育"],
      ["單輪車", "Unicycle", "體育"],
      ["手鐘", "Handchimes", "藝術"],
      ["乒乓球", "Table Tennis", "體育"],
      ["跳繩", "Rope Skipping", "體育"],
      ["Drama Club", "Drama Club", "學術"],
      ["桌樂冒險家", "Tabletop Adventure", "藝術"],
      ["社會服務團", "Social Service Group", "學術"],
      ["日文班", "Japanese Class", "學術"],
      ["小提琴(2)", "Violin (2)", "藝術"],
      ["合唱團", "Choir", "藝術"],
      ["跳舞", "Dance", "藝術"],
      ["滑板", "Skateboarding", "體育"],
      ["田徑", "Athletics", "體育"],
      ["欖球", "Rugby", "體育"],
    ],
    fri: [
      ["女子籃球", "Girls Basketball", "體育"],
      ["男子籃球", "Boys Basketball", "體育"],
      ["樂團", "School Band", "藝術"],
      ["匹克球", "Pickleball", "體育"],
      ["Newspaper Club", "Newspaper Club", "學術"],
      ["氣球造型班", "Balloon Twisting", "藝術"],
      ["英文集誦", "English Choral Speaking", "學術"],
      ["德文班", "German Class", "學術"],
      ["韓文班", "Korean Class", "學術"],
      ["銅管樂", "Brass", "藝術"],
      ["管樂班", "Wind Band", "藝術"],
      ["劍擊", "Fencing", "體育"],
      ["棍網球", "Lacrosse", "體育"],
      ["足球", "Football", "體育"],
    ],
  },
};
